---
title: "DT_table_for_suppfiles"
author: "arman"
date: "2020-12-14"
output: workflowr::wflow_html
editor_options:
  chunk_output_type: console
---

## here I will build a stock table; wrap it in a function or create a standard way to show tables 


```{r}

library(DT)
library(tidyverse)

CPI2 <- readRDS("~/Statcan/R_projects/Supplemenetary_data_files_automation_v2/output/RDSobjects/CPI2.rds")

datatable(
  iris,
  extensions = c("ColReorder", "Buttons"), options = list(
    colReorder = TRUE,
    dom = "Bfrtip",
    buttons = c("copy", "csv", "excel"),
    searchHighlight = TRUE
  ),
  filter = "top"
)
```


 ## Wrapping it up in a function
 
```{r}
interactive_table <- function(data) {
DT::datatable(
  {{data}},
  extensions = c("ColReorder", "Buttons"), options = list(
    colReorder = TRUE,
    dom = "Bfrtip",
    buttons = c("copy", "csv",I("colvis")),
    searchHighlight = TRUE,
    search = list(regex = TRUE)
  ),
  filter = "top"
)
  }

interactive_table(gapminder::gapminder)
```
 
 
Using searh panes 


```{r}
library(DT)
datatable(
  iris,
  options = list(dom = "Pfrtip", columnDefs = list(list(
    searchPanes = list(show = FALSE), targets = 0:3
  ))),
  extensions = c("Select", "SearchPanes"),
  selection = "none"
)

datatable(
  CPI2,
  extensions = c("ColReorder", "Buttons", "Select", "SearchPanes"), options = list(
    colReorder = TRUE,
    dom = "Pfrtip", dom = "Bfrtip",
    columnDefs = list(list(
      searchPanes = list(cascadePanes = TRUE), targets = 1:6
    )),
    buttons = c("copy", "csv", "excel"),
    dom = "Bfrtip",
    searchHighlight = TRUE
  ),
  filter = "top",
  selection = "none"
)
```



## using cross talk 

```{r}
library(crosstalk)
library(plotly)
sd <- SharedData$new(iris)
interactive_table <- function(data) {
  DT::datatable(
    {{ data }},
    extensions = c("ColReorder", "Buttons"), options = list(
      colReorder = TRUE,
      dom = "Bfrtip",
      buttons = c("copy", "csv", "excel"),
      searchHighlight = TRUE
    ),
    filter = "top"
  )
}

interactive_table(sd)

```


```{r}
library(crosstalk)
library(plotly)

# generally speaking, use a "unique" key for filter, 
# especially when you have multiple filters!
tx <- highlight_key(txhousing)
gg <- ggplot(tx) + geom_line(aes(date, median, group = city))
filter <- bscols(
  filter_select("id", "Select a city", tx, ~city),
  ggplotly(gg, dynamicTicks = TRUE),
  widths = c(12, 12)
)

tx2 <- highlight_key(txhousing, ~city, "Select a city")
gg <- ggplot(tx2) + geom_line(aes(date, median, group = city))
select <- highlight(
  ggplotly(gg, tooltip = "city"), 
  selectize = TRUE, persistent = TRUE)

table <- interactive_table(tx2)
bscols(filter, select, table)
```

